######################################################################
# Automatically generated by qmake (3.0) pon. maj 26 19:20:35 2014
######################################################################

TEMPLATE = lib
TARGET = ../lib/GUI
INCLUDEPATH += .
OBJECTS_DIR = ../obj
MOC_DIR = ../moc
QT += qml quick widgets

# Input
HEADERS += GUI.hpp
SOURCES += GUI.cpp
